version: "3.11"
services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres-db
    ports:
      - "8000:8000"
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload

  postgres-db:
    image: ankane/pgvector
    container_name: postgres-db
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}


volumes:
  postgres_volume: